services:
  # PostgreSQL database for LangGraph and metadata
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aegra
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d aegra"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Aegra Server
  aegra:
    build:
      context: .
      dockerfile: deployments/docker/Dockerfile
    extra_hosts: #added by Michal Riha
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/aegra
      - AUTH_TYPE=noop
      - DEBUG=true
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./aegra.json:/app/aegra.json:ro
      - ./graphs:/app/graphs:ro
      - ./src:/app/src:ro # for hot reload support of server
      - ./auth.py:/app/auth.py:ro
      - ./.env:/app/.env:ro
      - ./alembic:/app/alembic:ro # for migrations
    command: >
      sh -c "
        echo 'Running database migrations...' &&
        alembic upgrade head &&
        echo 'Starting Aegra server...' &&
        python -m debugpy --listen 0.0.0.0:5678 -m uvicorn src.agent_server.main:app --host 0.0.0.0 --port 8000 --reload
      "

  # Redis (optional - for advanced queuing in future phases)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    profiles:
      - redis

volumes:
  postgres_data:
  redis_data:
